name: the_zone
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '2.0.0-beta.3'
  browser: '^0.10.0'
  bootstrap: '^3.3.4'
  firebase: '^0.6.5+1'
  github: '^2.3.1+1'
  dogma_convert: '^0.0.1'
  dart_to_js_script_rewriter: '^0.1.0+4'
  logging: '^0.11.2'
  intl: '^0.12.7'
dev_dependencies:
  grinder: '^0.8.0+2'
  git: '^0.4.4+2'
  dogma_codegen: '^0.0.2'
  watcher: '^0.9.7'
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/router.dart#ROUTER_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
dependency_overrides:
  analyzer: 0.27.1