name: the_zone
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '2.0.0-beta.3'
  browser: '^0.10.0'
  bootstrap: '^3.3.4'
dev_dependencies:
  grinder: '^0.8.0+2'
  git: '^0.4.4+2'
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
